pub const MAGIC: &[u8; 8] = b"POISNAP\0";
pub const FORMAT_VERSION: u16 = 3;

pub const MAGIC_OFFSET: usize = 0;
pub const MAGIC_BYTES: usize = 8;
pub const FORMAT_VERSION_OFFSET: usize = MAGIC_OFFSET + MAGIC_BYTES;
pub const FORMAT_VERSION_BYTES: usize = 2;
pub const HEADER_LEN_OFFSET: usize = FORMAT_VERSION_OFFSET + FORMAT_VERSION_BYTES;
pub const HEADER_LEN_BYTES: usize = 2;
pub const CHAIN_TYPE_OFFSET: usize = HEADER_LEN_OFFSET + HEADER_LEN_BYTES;
pub const CHAIN_TYPE_BYTES: usize = 1;
pub const SNAPSHOT_KIND_OFFSET: usize = CHAIN_TYPE_OFFSET + CHAIN_TYPE_BYTES;
pub const SNAPSHOT_KIND_BYTES: usize = 1;
pub const RESERVED_OFFSET: usize = SNAPSHOT_KIND_OFFSET + SNAPSHOT_KIND_BYTES;
pub const RESERVED_BYTES: usize = 2;
pub const LIST_KEY_OFFSET: usize = RESERVED_OFFSET + RESERVED_BYTES;
pub const LIST_KEY_BYTES: usize = 32;
pub const CHAIN_ID_OFFSET: usize = LIST_KEY_OFFSET + LIST_KEY_BYTES;
pub const CHAIN_ID_BYTES: usize = 8;
pub const START_INDEX_OFFSET: usize = CHAIN_ID_OFFSET + CHAIN_ID_BYTES;
pub const START_INDEX_BYTES: usize = 8;
pub const END_INDEX_OFFSET: usize = START_INDEX_OFFSET + START_INDEX_BYTES;
pub const END_INDEX_BYTES: usize = 8;
pub const EVENT_COUNT_OFFSET: usize = END_INDEX_OFFSET + END_INDEX_BYTES;
pub const EVENT_COUNT_BYTES: usize = 8;
pub const BLOCKED_SHIELD_COUNT_OFFSET: usize = EVENT_COUNT_OFFSET + EVENT_COUNT_BYTES;
pub const BLOCKED_SHIELD_COUNT_BYTES: usize = 8;
pub const TIP_MERKLEROOT_OFFSET: usize = BLOCKED_SHIELD_COUNT_OFFSET + BLOCKED_SHIELD_COUNT_BYTES;
pub const TIP_MERKLEROOT_BYTES: usize = 32;
pub const UPSTREAM_ENDPOINT_HASH_OFFSET: usize = TIP_MERKLEROOT_OFFSET + TIP_MERKLEROOT_BYTES;
pub const UPSTREAM_ENDPOINT_HASH_BYTES: usize = 32;
pub const CREATED_AT_OFFSET: usize = UPSTREAM_ENDPOINT_HASH_OFFSET + UPSTREAM_ENDPOINT_HASH_BYTES;
pub const CREATED_AT_BYTES: usize = 8;
pub const EVENTS_OFFSET_OFFSET: usize = CREATED_AT_OFFSET + CREATED_AT_BYTES;
pub const EVENTS_OFFSET_BYTES: usize = 8;
pub const BLOCKED_SHIELDS_OFFSET_OFFSET: usize = EVENTS_OFFSET_OFFSET + EVENTS_OFFSET_BYTES;
pub const BLOCKED_SHIELDS_OFFSET_BYTES: usize = 8;
pub const HEADER_LEN: usize = BLOCKED_SHIELDS_OFFSET_OFFSET + BLOCKED_SHIELDS_OFFSET_BYTES;
pub const HEADER_LEN_U16: u16 = 176;
pub const HEADER_LEN_U64: u64 = 176;

pub const EVENT_BLINDED_COMMITMENT_OFFSET: usize = 0;
pub const EVENT_BLINDED_COMMITMENT_BYTES: usize = 32;
pub const EVENT_SIGNATURE_OFFSET: usize =
    EVENT_BLINDED_COMMITMENT_OFFSET + EVENT_BLINDED_COMMITMENT_BYTES;
pub const EVENT_SIGNATURE_BYTES: usize = 64;
pub const EVENT_TYPE_OFFSET: usize = EVENT_SIGNATURE_OFFSET + EVENT_SIGNATURE_BYTES;
pub const EVENT_TYPE_BYTES: usize = 1;
pub const EVENT_RECORD_BYTES: usize = EVENT_TYPE_OFFSET + EVENT_TYPE_BYTES;
pub const EVENT_RECORD_BYTES_U64: u64 = 97;

pub const BLOCKED_COMMITMENT_HASH_OFFSET: usize = 0;
pub const BLOCKED_COMMITMENT_HASH_BYTES: usize = 32;
pub const BLOCKED_BLINDED_COMMITMENT_OFFSET: usize =
    BLOCKED_COMMITMENT_HASH_OFFSET + BLOCKED_COMMITMENT_HASH_BYTES;
pub const BLOCKED_BLINDED_COMMITMENT_BYTES: usize = 32;
pub const BLOCKED_SIGNATURE_OFFSET: usize =
    BLOCKED_BLINDED_COMMITMENT_OFFSET + BLOCKED_BLINDED_COMMITMENT_BYTES;
pub const BLOCKED_SIGNATURE_BYTES: usize = 64;
pub const BLOCKED_REASON_PRESENT_OFFSET: usize = BLOCKED_SIGNATURE_OFFSET + BLOCKED_SIGNATURE_BYTES;
pub const BLOCKED_REASON_PRESENT_BYTES: usize = 1;
pub const BLOCKED_REASON_LEN_OFFSET: usize =
    BLOCKED_REASON_PRESENT_OFFSET + BLOCKED_REASON_PRESENT_BYTES;
pub const BLOCKED_REASON_LEN_BYTES: usize = 4;
pub const BLOCKED_SHIELD_FIXED_RECORD_BYTES: usize = BLOCKED_REASON_PRESENT_OFFSET + 1;
pub const BLOCKED_REASON_ABSENT: u8 = 0;
pub const BLOCKED_REASON_PRESENT: u8 = 1;
